### ISSUE TITLE
Installation fails on yunohost 11.1.02

### ISSUE THREAD

**Issue by centralscrutinizer21** [YunoHost-Apps/mobilizon_ynh#150]
### Describe the bug

Installation fails after WARNING 

### Context

- Hardware: VPS bought online & Raspberry Pi at home
- YunoHost version: 11.1.02
- I have access to my server: Through SSH | through the webadmin | 
- Are you in a special context or did you perform some particolar tweaking on your YunoHost instance?: no

### Steps to reproduce

Both cli installation and via webadmin interface
give a `WARNING  - Not a tty, can't do interactive prompts`
After that Installation fails.

### Logs
https://paste.yunohost.org/raw/etuhirefuv

**Comment by nebocamin** [comment]
can confirm
https://paste.yunohost.org/raw/toqegepaku

**Comment by rodinux** [comment]
I have found this bug, and resolve it on a fork here. It is explain why on 11.1 it fails, but be aware it is a temporally fix, on future release for the branch testing, the option `yunohost user create  --fisrtname=""` and `yunohost user create  --fisrtname=""` will be implemented again...

Take a look here: https://github.com/YunoHost-Apps/mobilizon_ynh/pulls

For now, you can just use my fork like this `sudo yunohost app install https://github.com/rodinux/mobilizon_ynh` and wait the fix for `yunohost user create  --fisrtname=""` and `yunohost user create  --fisrtname=""`...

**Comment by centralscrutinizer21** [comment]
> can confirm https://paste.yunohost.org/raw/toqegepaku
> 
> update: i am on testing. you too @centralscrutinizer21 ? on another yunohost, it worked well.

@nebocamin Yes testing version

**Comment by yalh76** [comment]
would be fixed when YunoHost stable 11.1 will be released

**Comment by yalh76** [comment]
> It is fixed since version 11.1.1.2

11.1.1.2 is a stable or testing version ?

**Comment by rodinux** [comment]
> 11.1.1.2 is a stable or testing version ?

I have released some time ago my version adding the testing branch to upgrade to version 11.1.1.2, to fix this problem.

```
yunohost: 
  repo: testing
  version: 11.1.1.2
yunohost-admin: 
  repo: testing
  version: 11.1.1
moulinette: 
  repo: testing
  version: 11.1.0
ssowat: 
  repo: testing
  version: 11.1.0
```
But I come back after to stable version
 `deb http://forge.yunohost.org/debian/ bullseye stable`

**Comment by yalh76** [comment]
ok then, 11.1.1.2 is still a testing version
